version: '3.8'

services:
  # Redis Master
  redis-master:
    image: redis:7-alpine
    container_name: ocean-redis-master
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 0
      --requirepass ${REDIS_PASSWORD:-oceanshoppingredis}
      --masterauth ${REDIS_PASSWORD:-oceanshoppingredis}
    volumes:
      - redis-master-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - redis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-oceanshoppingredis}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Slave 1
  redis-slave-1:
    image: redis:7-alpine
    container_name: ocean-redis-slave-1
    command: >
      redis-server
      --slaveof redis-master 6379
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 0
      --requirepass ${REDIS_PASSWORD:-oceanshoppingredis}
      --masterauth ${REDIS_PASSWORD:-oceanshoppingredis}
    volumes:
      - redis-slave-1-data:/data
    ports:
      - "6380:6379"
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-oceanshoppingredis}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Slave 2
  redis-slave-2:
    image: redis:7-alpine
    container_name: ocean-redis-slave-2
    command: >
      redis-server
      --slaveof redis-master 6379
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 0
      --requirepass ${REDIS_PASSWORD:-oceanshoppingredis}
      --masterauth ${REDIS_PASSWORD:-oceanshoppingredis}
    volumes:
      - redis-slave-2-data:/data
    ports:
      - "6381:6379"
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-oceanshoppingredis}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Sentinel 1
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: ocean-redis-sentinel-1
    command: >
      redis-sentinel /usr/local/etc/redis/sentinel.conf
      --sentinel
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
    ports:
      - "26379:26379"
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "sentinel", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Sentinel 2
  redis-sentinel-2:
    image: redis:7-alpine
    container_name: ocean-redis-sentinel-2
    command: >
      redis-sentinel /usr/local/etc/redis/sentinel.conf
      --sentinel
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
    ports:
      - "26380:26379"
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "sentinel", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Sentinel 3
  redis-sentinel-3:
    image: redis:7-alpine
    container_name: ocean-redis-sentinel-3
    command: >
      redis-sentinel /usr/local/etc/redis/sentinel.conf
      --sentinel
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
    ports:
      - "26381:26379"
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "sentinel", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Exporter for Prometheus monitoring
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: ocean-redis-exporter
    environment:
      - REDIS_ADDR=redis://redis-master:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-oceanshoppingredis}
    ports:
      - "9121:9121"
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped

volumes:
  redis-master-data:
    driver: local
  redis-slave-1-data:
    driver: local
  redis-slave-2-data:
    driver: local

networks:
  redis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16